//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::youtube_backgrounder::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::youtube_backgrounder::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->MenuSplitView = safe_cast<::Windows::UI::Xaml::Controls::SplitView^>(__target);
            }
            break;
        case 2:
            {
                this->MenuButton = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(this->MenuButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::youtube_backgrounder::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::MenuButton_Click);
            }
            break;
        case 3:
            {
                this->SearchButton = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(this->SearchButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::youtube_backgrounder::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::SearchButton_Click);
            }
            break;
        case 4:
            {
                this->PlayerButton = safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::RadioButton^>(this->PlayerButton))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::youtube_backgrounder::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PlayerButton_Click);
            }
            break;
        case 5:
            {
                ::Windows::UI::Xaml::Controls::SearchBox^ element5 = safe_cast<::Windows::UI::Xaml::Controls::SearchBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::SearchBox^>(element5))->QuerySubmitted += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::SearchBox^, ::Windows::UI::Xaml::Controls::SearchBoxQuerySubmittedEventArgs^>(this, (void (::youtube_backgrounder::MainPage::*)
                    (::Windows::UI::Xaml::Controls::SearchBox^, ::Windows::UI::Xaml::Controls::SearchBoxQuerySubmittedEventArgs^))&MainPage::SearchSugesstion);
            }
            break;
        case 6:
            {
                this->SplitViewFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::youtube_backgrounder::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


