//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "SearchPage.xaml.h"

void ::youtube_backgrounder::SearchPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///SearchPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::youtube_backgrounder::SearchPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->grid_main = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
        }
        break;
    case 3:
        {
            this->scrollResult = safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ScrollViewer^>(this->scrollResult))->ViewChanged += ref new ::Windows::Foundation::EventHandler<::Windows::UI::Xaml::Controls::ScrollViewerViewChangedEventArgs^>(this, (void (::youtube_backgrounder::SearchPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::ScrollViewerViewChangedEventArgs^))&SearchPage::scrollResult_ViewChanged);
        }
        break;
    case 4:
        {
            this->gridresult = safe_cast<::Windows::UI::Xaml::Controls::GridView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::GridView^>(this->gridresult))->ItemClick += ref new ::Windows::UI::Xaml::Controls::ItemClickEventHandler(this, (void (::youtube_backgrounder::SearchPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::ItemClickEventArgs^))&SearchPage::gridresult_ItemClick);
        }
        break;
    case 5:
        {
            ::Windows::UI::Xaml::Controls::ItemsWrapGrid^ element5 = safe_cast<::Windows::UI::Xaml::Controls::ItemsWrapGrid^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::ItemsWrapGrid^>(element5))->SizeChanged += ref new ::Windows::UI::Xaml::SizeChangedEventHandler(this, (void (::youtube_backgrounder::SearchPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::SizeChangedEventArgs^))&SearchPage::ItemsWrapGrid_SizeChanged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::youtube_backgrounder::SearchPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


