#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class MediaElement;
                ref class ScrollViewer;
                ref class GridView;
            }
        }
    }
}

namespace youtube_backgrounder
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class SearchPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ grid_main;
        private: ::Windows::UI::Xaml::Controls::MediaElement^ musicPlayer;
        private: ::Windows::UI::Xaml::Controls::ScrollViewer^ scroll;
        private: ::Windows::UI::Xaml::Controls::GridView^ gridresult;
    };
}

